/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface;

import control.ClientControl;
import control.DatabaseControl;
import control.TimeControl;
import java.io.IOException;

/**
 *
 * @author nathancezar
 */
public class AdminFrame extends javax.swing.JFrame {

    private static TimeControl timeControl = TimeControl.getTimeControl();
    private static ClientControl clientControl = ClientControl.getClientControl();
    private static DatabaseControl dataBaseControl = DatabaseControl.getDatabaseControl();

    /**
     * Creates new form BankView
     */
    public AdminFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        buttonClientRegister = new javax.swing.JButton();
        buttonUnblockCard = new javax.swing.JButton();
        buttonCardInformation = new javax.swing.JButton();
        buttonListItems = new javax.swing.JButton();
        buttonGetClient = new javax.swing.JButton();
        buttonGetAllClients = new javax.swing.JButton();
        buttonTurnMonths = new javax.swing.JButton();
        buttonBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(1, 1, 1));
        setPreferredSize(new java.awt.Dimension(350, 150));
        setResizable(false);

        buttonClientRegister.setFont(new java.awt.Font("Courier 10 Pitch", 0, 12)); // NOI18N
        buttonClientRegister.setText("Registrar Clientes");
        buttonClientRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonClientRegisterActionPerformed(evt);
            }
        });

        buttonUnblockCard.setFont(new java.awt.Font("Courier 10 Pitch", 0, 12)); // NOI18N
        buttonUnblockCard.setText("Desbloquear Cartão");
        buttonUnblockCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUnblockCardActionPerformed(evt);
            }
        });

        buttonCardInformation.setFont(new java.awt.Font("Courier 10 Pitch", 0, 12)); // NOI18N
        buttonCardInformation.setText("Informações do Cartão");
        buttonCardInformation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCardInformationActionPerformed(evt);
            }
        });

        buttonListItems.setFont(new java.awt.Font("Courier 10 Pitch", 0, 12)); // NOI18N
        buttonListItems.setText("Listar Itens do Cartão");
        buttonListItems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonListItemsActionPerformed(evt);
            }
        });

        buttonGetClient.setFont(new java.awt.Font("Courier 10 Pitch", 0, 12)); // NOI18N
        buttonGetClient.setText("Buscar Cliente");
        buttonGetClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGetClientActionPerformed(evt);
            }
        });

        buttonGetAllClients.setFont(new java.awt.Font("Courier 10 Pitch", 0, 12)); // NOI18N
        buttonGetAllClients.setText("Listar Clientes");
        buttonGetAllClients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGetAllClientsActionPerformed(evt);
            }
        });

        buttonTurnMonths.setFont(new java.awt.Font("Courier 10 Pitch", 0, 12)); // NOI18N
        buttonTurnMonths.setText("Virar Mês");
        buttonTurnMonths.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTurnMonthsActionPerformed(evt);
            }
        });

        buttonBack.setBackground(java.awt.Color.red);
        buttonBack.setFont(new java.awt.Font("Courier 10 Pitch", 0, 12)); // NOI18N
        buttonBack.setForeground(java.awt.Color.black);
        buttonBack.setText("Voltar");
        buttonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBackActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Courier 10 Pitch", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Admin Panel");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buttonClientRegister, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonUnblockCard, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonCardInformation, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonListItems, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(buttonTurnMonths, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonGetAllClients, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                    .addComponent(buttonBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonGetClient, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonClientRegister)
                    .addComponent(buttonGetClient))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonUnblockCard)
                    .addComponent(buttonGetAllClients))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonCardInformation)
                    .addComponent(buttonTurnMonths))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonListItems)
                    .addComponent(buttonBack))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        getAccessibleContext().setAccessibleName("Bank Menu");
        getAccessibleContext().setAccessibleDescription("Bank Menu");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonClientRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonClientRegisterActionPerformed

    }//GEN-LAST:event_buttonClientRegisterActionPerformed

    private void buttonUnblockCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUnblockCardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonUnblockCardActionPerformed

    private void buttonCardInformationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCardInformationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonCardInformationActionPerformed

    private void buttonListItemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonListItemsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonListItemsActionPerformed

    private void buttonGetClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGetClientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonGetClientActionPerformed

    private void buttonGetAllClientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGetAllClientsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonGetAllClientsActionPerformed

    private void buttonTurnMonthsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTurnMonthsActionPerformed
        timeControl.turnMonth(clientControl.returnClientSet());
        try {
            dataBaseControl.WriteList(clientControl.returnClientSet(), "clientes.bin");
        } catch (IOException ex) {
            System.out.println("Ocorreu algum erro durante a gravação dos arquivos!");
        }
    }//GEN-LAST:event_buttonTurnMonthsActionPerformed

    private void buttonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBackActionPerformed
        this.dispose();
    }//GEN-LAST:event_buttonBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBack;
    private javax.swing.JButton buttonCardInformation;
    private javax.swing.JButton buttonClientRegister;
    private javax.swing.JButton buttonGetAllClients;
    private javax.swing.JButton buttonGetClient;
    private javax.swing.JButton buttonListItems;
    private javax.swing.JButton buttonTurnMonths;
    private javax.swing.JButton buttonUnblockCard;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
